### PR TITLE
Modified iam_role so that existing instance profiles return valid ARN.

### PR DESCRIPTION
**Pull request by cullenbass**
This patch is to fix an issue with the ALKS terraform provider. The instance profile ARN from an existing IAM role was assumed to be formatted correctly form ALKS, but ALKS returns a Java array formatted into a string. I used regex to pull the ARN out of the poorly formatted string and return that instead of the raw response.

### CODE REVIEW

**Comment by brianantonelli** [comment]
Looks like it's failing the test.. We dont have this testing against live data in Travis currently. I'll look into this PR next week as the ALKS API is now returning better errors so theres a few things that need to be updated.

**Comment by cullenbass** [comment]
Sounds good. I've gotten the terraform provider compiling and working on a clean gopath, but I only have access to test on the live ALKS API, so I can't test against any upcoming changes.

**Comment by brianantonelli** [comment]
Yeah what you wrote should be good, its just failing the mock tests.

**Comment by brianantonelli** [comment]
Merging into a temporary branch to fix a few issues with this patch.

**Comment by brianantonelli** [comment]
This is now merged into master and will be included in the next ALKS Terraform Provider build. See #2

**Pull request merged**
